### ISSUE TITLE
mask_coefficient

### ISSUE THREAD

**Issue by SiHui05** [lose4578/SAM-DiffSR#5]
![613f82743ca43270157b2de164fa052](https://github.com/lose4578/SAM-DiffSR/assets/162797162/5e4f660a-6428-43aa-8ec5-6ea401d41531)
self.mask_coefficient = to_torch(np.sqrt(1. - alphas_cumprod) * betas)
Could you tell me why the coefficient of the mask in the code is different from the one in the paper please? Thank you very much.

**Comment by lose4578** [comment]
This is a bug, and you can fix it.
In out experiment, this coefficient has little effect on the final results.
