### ISSUE TITLE
How much cuda memory for inference?

### ISSUE THREAD

**Issue by YoucanBaby** [lose4578/SAM-DiffSR#7]
Dear developer,

Thanks for your nice project.

I use 3090 (24GB) for inference and get the error:  'CUDA out of memory'.

How much cuda memory does this project require for inference?

**Comment by lose4578** [comment]
When you inference the DIV2K dataset(510x340) with X4 super-resolution, you need about 12G GPU memory. If you inference for larger resolution images, you need more GPU memory.

**Comment by YoucanBaby** [comment]
> When you inference the DIV2K dataset(510x340) with X4 super-resolution, you need about 12G GPU memory. If you inference for larger resolution images, you need more GPU memory.

I use 1024x1024. 24GB menory is not enough.
