### ISSUE TITLE
关于数据准备

### ISSUE THREAD

**Issue by Shaosifan** [lose4578/SAM-DiffSR#8]
感谢作者的工作！关于数据准备过程中，遇到一个问题，就是从SPE转成RLE中，发现SAM代码库中没有merge_mask_to_one.py这个文件，使用本代码data_gen文件夹下的merge_mask_to_one.py来运行，发现出不了结果，显示如下：
```
0it [00:00, ?it/s]
Processing ../data/sam_out/DF2K/DF2K_train_HR...
```
请问这是因为什么问题呢？

**Comment by lose4578** [comment]
Can you provide the complete command and log? Or you can try to use the absolute path.

**Comment by Shaosifan** [comment]
> Can you provide the complete command and log? Or you can try to use the absolute path.

Thanks for your reply. It works when using the absolute path.
