### ISSUE TITLE
掩码的系数

### ISSUE THREAD

**Issue by applied-chemistry** [lose4578/SAM-DiffSR#9]
为什么代码里计算损失函数时掩码的系数是self.mask_coefficient = to_torch(np.sqrt(1. - alphas_cumprod) * betas)，而论文里的是
![image](https://github.com/user-attachments/assets/b725a5e0-a453-4e46-a75c-dd706de4b1d5)
我的理解应该是self.mask_coefficient = to_torch(np.sqrt((1. - alphas_cumprod) / betas))，还望大佬解答

**Comment by lose4578** [comment]
You are right, and you can fix it in your code. And in out  experiment, this coefficient has little effect on the final results.
